language: objective-c
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=CryptoSwift.xcworkspace
  - IOS_SCHEME="CryptoSwift iOS"
  - OSX_SCHEME="CryptoSwift OSX"
  - TVOS_SCHEME="CryptoSwift tvOS"
  - WATCHOS_SCHEME="CryptoSwift watchOS"
  - IOS_SIM="iphonesimulator"
  - OSX_SIM="macosx"
  - TVOS_SIM="appletvsimulator"
  - WATCHOS_SIM="watchsimulator"
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: DESTINATION="OS=9.3,name=iPhone 6S Plus" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}9.3"

    - os: osx
      osx_image: xcode8
      env: DESTINATION="OS=10.0,name=iPhone 6S" SCHEME="$IOS_SCHEME" SDK="${IOS_SIM}10.0"

    - os: linux
      dist: trusty
      sudo: required
      language: generic
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - ./scripts/CI.sh

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean test | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean test | xcpretty -c;
